//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoctorTodaySchedule
    {
        public int AppointmentId { get; set; }
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string Specialization { get; set; }
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string PatientPhone { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> PatientAge { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string AppointmentTime { get; set; }
        public int HourOfDay { get; set; }
        public int MinuteOfHour { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
    }
}
