//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PatientClinicalSummary
    {
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string InsuranceNumber { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CompletedVisits { get; set; }
        public Nullable<int> CancelledVisits { get; set; }
        public Nullable<System.DateTime> LastVisitDate { get; set; }
        public string LastSeenDoctor { get; set; }
        public Nullable<System.DateTime> NextAppointmentDate { get; set; }
    }
}
