//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicManagement_proj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PatientRecordsSummary
    {
        public Nullable<long> VisitNumber { get; set; }
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string InsuranceNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string DoctorName { get; set; }
        public string Specialization { get; set; }
        public string VisitStatus { get; set; }
        public string ClinicalNotes { get; set; }
        public Nullable<int> DaysSinceVisit { get; set; }
    }
}
